# Generated by Django 3.0.8 on 2020-08-02 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0006_aula'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='vimeo_id',
            field=models.CharField(default=1, max_length=32),
        ),
    ]
